# 项目配置

paths:
  # 原始数据路径
  raw_data: "D:/WindModelV1.8.7/data/raw/Turbine_Data.csv"
  # 模型保存位置
  model_save_path: "models/wind_model.joblib"
  # 结果输出目录
  results_dir: "results/"

# 训练参数
model_params:
  learning_rate: 0.01
  n_estimators: 8000
  num_leaves: 128
  max_depth: 8
  lambda_l1: 0.2             # L1正则
  lambda_l2: 1               # L2正则
  min_child_samples: 50
  bagging_fraction: 0.8
  feature_fraction: 0.8
  early_stopping_rounds: 100
  random_state: 42

# 预测任务配置
forecast_config:
  look_ahead_steps: 144       # 预测未来n*10分钟（n为输入值）
  test_size: 0.2            # 20%作为测试集
  capacity_kw: 1720           # 额定功率

# 数据清洗黑名单
exclude_columns:
  - 'WTG'
  - 'Reactive Power'
  - 'Rotor RPM'

# 变量选择配置
feature_selection:
  mode: "manual"            #top_n or manual
  manual_features:
    - 'WindSpeed'
    - 'future_ws_144'
    - 'future_ws_24'
    - 'ws_squared'
    - 'ws_cubed'
    - 'hour_sin'
    - 'hour_cos'
    #- 'wd_sin'
    #- 'wd_cos'
    #- 'AmbientTemperatue'
    - 'power_lag_1'
    - 'power_lag_6'
    - 'power_lag_24'
    - 'power_lag_144'
    - 'power_rolling_mean_6'
    - 'power_diff_1'
    - 'power_rolling_std_6'
    - 'power_rolling_kurt_12'
    - 'ws_diff_1'
    - 'ws_rolling_std_6'

top_n_count: 8          # 当 mode 为 "top_n" 时生效，选取相关性最高的n个特征

#噪声处理设置
noise_processing:
  enabled: true
  columns:
    - "WindSpeed"
    - "ActivePower"
  iqr_k: 1.5
  smooth_window: 5
  spike_threshold: 10

